# .github/workflows/publish.yml
name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # Déclenche sur les tags qui commencent par 'v'
  release:
    types: [published]
  workflow_dispatch:  # Permet de déclencher manuellement

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/dedsec-decoder
    permissions:
      id-token: write  # Nécessaire pour l'authentification OIDC PyPI

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: python -m build

    - name: Check package
      run: |
        twine check dist/*
        
    - name: Test package installation
      run: |
        python -m pip install dist/*.whl
        python -c "import dedsec_decoder; print(dedsec_decoder.__version__)"

    - name: Publish to Test PyPI
      if: github.event_name == 'workflow_dispatch'  # Seulement lors d'un déclenchement manuel
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        verbose: true
        skip-existing: true

    - name: Publish to PyPI
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verbose: true
